book <- read.csv("C:/Users/Yogesh/Downloads/book (4).csv")
View(book)
summary(book)
install.packages("arules")
library(arules)
install.packages("arulesViz")
library(arulesViz)
data<-as.matrix(book)
data2<-as(data, "transactions")
arules<-apriori(data2 ,parameter = list(support=0.02,confidence=0.6,minlen=2))
inspect(arules[1:20,])
inspect(sort(arules,by="lift"))
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:7],method = "graph")
write(arules,file = "rules.csv",sep=",")
getwd()
