install.packages("arules")
data()
library(arules)
data("Groceries")
?Groceries
inspect(Groceries[1:10])
class(Groceries)
summary(Groceries)
itemFrequencyPlot(Groceries,topN =10,col ="blue")
install.packages("aruleviz")
library(arulesViz)
arules<-apriori(Groceries,parameter = list(support =0.002,confidence =0.6,minlen =2))
arules
inspect(arules[1:10])
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:7],method = "graph")
write(arules,file = "a_rules.csv",sep=",")
getwd()
