mba <- read.csv("C:/Users/Yogesh/Downloads/mba.csv")
View(mba)
summary(mba)
barplot(mba$gmat)
barplot(mba$workex)
hist(mba$gmat)
hist(mba$workex)
boxplot(mba$gmat)
boxplot(mba$workex)
boxplot(mba$gmat, vertical=TRUE)
mean(mba$workex)
sd(mba$workex)
qqnorm(mba$workex)
qqline(mba$workex)
qqnorm(mba$gmat)
qqline(mba$gmat)
logtransform<-sqrt(mba$workex)
qqnorm(logtransform)
qqline(logtransform)
sqrttran<-sqrt(mba$workex)
qqnorm(sqrttran)
?log
?qqline
standardised_gmat<-scale(mba$gmat)
View(standardised_gmat)
