install.packages("readxl")
library(readxl)
Promotion <- read_excel("C:/Users/Yogesh/Downloads/Promotion (2).xlsx")
View(Promotion)
attach(Promotion)
colnames(Promotion)<-c("credit","promotion.Type","InterestRateWaiver","StandardPromotion")
View(Promotion)
attach(Promotion)
shapiro.test(InterestRateWaiver)
shapiro.test(StandardPromotion)
var.test(InterestRateWaiver,StandardPromotion)
t.test(InterestRateWaiver,StandardPromotion, alternative = "two.sided", conf.level = 0.95, correct = TRUE)
t.test(InterestRateWaiver,StandardPromotion, alternative = "greater", var.equal = TRUE)
